version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/bm-tslint-rules

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found

      - run: npm install

#      - save_cache:
#          paths:
#            - node_modules
#          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Perform tslint Check
          command: npm run tslint

      - run:
          name: build and create report
          command: |
            npm run build
            npm run report
            git add . # make sure line endings are sanitized by git
            git diff HEAD --exit-code

      - store_artifacts:
          path: tslint.report.active.json
          destination: tslint.report.active.json
      - store_artifacts:
          path: tslint.report.available.json
          destination: tslint.report.available.json
      - store_artifacts:
          path: tslint.report.sources.json
          destination: tslint.report.sources.json

      - run:
          name: run tests
          command: npm test
      - store_test_results:
          path: junit

      - run:
          name: check version different from master
          command: ./ci-test-master-version.sh
